# Generated by Django 5.2.9 on 2025-12-08 10:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_monitor", "0002_alter_monitoringroute_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wetlandzone",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="在地图上点击可自动填入经纬度",
                null=True,
                srid=4326,
                verbose_name="地图位置",
            ),
        ),
        migrations.AlterField(
            model_name="wetlandzone",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="纬度(y)"),
        ),
        migrations.AlterField(
            model_name="wetlandzone",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="经度(x)"),
        ),
    ]
