# Generated by Django 5.2.9 on 2025-12-10 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_monitor", "0004_remove_monitoringroute_path_coordinates_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="商品名称")),
                ("price", models.IntegerField(verbose_name="所需积分")),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="商品图片"),
                ),
                ("description", models.TextField(blank=True, verbose_name="商品描述")),
                ("stock", models.IntegerField(default=999, verbose_name="库存")),
            ],
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="points",
            new_name="score",
        ),
        migrations.AddField(
            model_name="observationrecord",
            name="uploader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_observations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传者",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="头像"
            ),
        ),
        migrations.AlterField(
            model_name="observationrecord",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_observations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上报人(旧)",
            ),
        ),
        migrations.AlterField(
            model_name="observationrecord",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已驳回")],
                default="pending",
                max_length=10,
                verbose_name="审核状态",
            ),
        ),
    ]
