# Generated by Django 5.2.9 on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_monitor", "0007_add_observation_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciesinfo",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="species/covers/",
                verbose_name="物种封面图",
            ),
        ),
    ]
