# Generated by Django 5.2.9 on 2025-12-08 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="ai_records/%Y/%m/", verbose_name="识别图片"
                    ),
                ),
                (
                    "species_name",
                    models.CharField(default="未知", max_length=50, verbose_name="识别结果"),
                ),
                ("confidence", models.FloatField(default=0.0, verbose_name="置信度")),
                (
                    "habit_info",
                    models.TextField(blank=True, null=True, verbose_name="习性简介"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="识别时间"),
                ),
            ],
            options={
                "verbose_name": "AI 识别记录",
                "verbose_name_plural": "AI 识别记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="路线名称")),
                ("path_coordinates", models.JSONField(verbose_name="路径坐标点集")),
                ("description", models.TextField(blank=True, verbose_name="路线说明")),
            ],
        ),
        migrations.CreateModel(
            name="SpeciesInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_cn",
                    models.CharField(max_length=100, unique=True, verbose_name="中文名"),
                ),
                (
                    "name_latin",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="拉丁名(species)"
                    ),
                ),
                (
                    "order",
                    models.CharField(blank=True, max_length=50, verbose_name="目"),
                ),
                (
                    "family",
                    models.CharField(blank=True, max_length=50, verbose_name="科"),
                ),
                (
                    "protection_level",
                    models.CharField(blank=True, max_length=20, verbose_name="保护级别"),
                ),
                (
                    "distribution_habit",
                    models.TextField(
                        blank=True,
                        default="暂无详细习性数据",
                        help_text="AI识别后展示给用户的本地化习性描述",
                        verbose_name="郑州湿地分布习性",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WetlandZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="点位名称"),
                ),
                ("longitude", models.FloatField(verbose_name="经度(x)")),
                ("latitude", models.FloatField(verbose_name="纬度(y)")),
                (
                    "is_hotspot",
                    models.BooleanField(default=False, verbose_name="今日推荐热点"),
                ),
                (
                    "observation_tips",
                    models.TextField(
                        blank=True, default="保持100米以上距离，避免干扰", verbose_name="观鸟注意事项"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0, verbose_name="当前积分")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation_time", models.DateField(verbose_name="观测日期")),
                ("count", models.IntegerField(default=1, verbose_name="数量(abundance)")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="observations/",
                        verbose_name="现场照片",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "待审核"), (1, "审核通过(已发积分)"), (2, "驳回")],
                        default=1,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上报人",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_monitor.speciesinfo",
                        verbose_name="物种",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_monitor.wetlandzone",
                        verbose_name="监测点位",
                    ),
                ),
            ],
            options={
                "ordering": ["-observation_time"],
            },
        ),
    ]
