# Generated by Django 5.2.9 on 2025-12-08 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_monitor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monitoringroute",
            options={"verbose_name": "监测样线", "verbose_name_plural": "监测样线"},
        ),
        migrations.AlterModelOptions(
            name="observationrecord",
            options={
                "ordering": ["-observation_time"],
                "verbose_name": "观测记录",
                "verbose_name_plural": "观测记录",
            },
        ),
        migrations.AlterModelOptions(
            name="speciesinfo",
            options={"verbose_name": "物种信息", "verbose_name_plural": "物种信息"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "用户积分档案", "verbose_name_plural": "用户积分档案"},
        ),
        migrations.AlterModelOptions(
            name="wetlandzone",
            options={"verbose_name": "监测点位", "verbose_name_plural": "监测点位"},
        ),
        migrations.AlterField(
            model_name="observationrecord",
            name="count",
            field=models.IntegerField(default=1, verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
