# Generated by Django 5.2.9 on 2025-12-08 11:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_monitor",
            "0003_wetlandzone_location_alter_wetlandzone_latitude_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitoringroute",
            name="path_coordinates",
        ),
        migrations.AddField(
            model_name="monitoringroute",
            name="path_geom",
            field=django.contrib.gis.db.models.fields.MultiLineStringField(
                blank=True, null=True, srid=4326, verbose_name="路线几何"
            ),
        ),
        migrations.AlterField(
            model_name="wetlandzone",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="SHP导入会自动填充此字段",
                null=True,
                srid=4326,
                verbose_name="地图位置",
            ),
        ),
    ]
