# Generated by Django 5.2.9 on 2025-12-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_monitor", "0005_product_rename_points_userprofile_score_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "积分商城商品", "verbose_name_plural": "积分商城商品"},
        ),
        migrations.AddField(
            model_name="observationrecord",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
    ]
